// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PEACE.api.Data;

#nullable disable

namespace PeaceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nutriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Subtipo")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AlimentoId");

                    b.ToTable("Nutriente");
                });

            modelBuilder.Entity("PEACE.api.Models.AcidosGraxosTaco", b =>
                {
                    b.Property<int>("NumeroAlimento")
                        .HasColumnType("integer");

                    b.Property<double?>("DezesseisUm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DezesseisZero")
                        .HasColumnType("double precision");

                    b.Property<double?>("DezoitoDoisN6")
                        .HasColumnType("double precision");

                    b.Property<double?>("DezoitoDoisT")
                        .HasColumnType("double precision");

                    b.Property<double?>("DezoitoTresN3")
                        .HasColumnType("double precision");

                    b.Property<double?>("DezoitoUm")
                        .HasColumnType("double precision");

                    b.Property<double?>("DezoitoUmT")
                        .HasColumnType("double precision");

                    b.Property<double?>("DezoitoZero")
                        .HasColumnType("double precision");

                    b.Property<double?>("DozeZero")
                        .HasColumnType("double precision");

                    b.Property<double?>("Monoinsaturados")
                        .HasColumnType("double precision");

                    b.Property<double?>("Poliinsaturados")
                        .HasColumnType("double precision");

                    b.Property<double?>("QuatorzeUm")
                        .HasColumnType("double precision");

                    b.Property<double?>("QuatorzeZero")
                        .HasColumnType("double precision");

                    b.Property<double?>("Saturados")
                        .HasColumnType("double precision");

                    b.Property<double?>("VinteCincoCinco")
                        .HasColumnType("double precision");

                    b.Property<double?>("VinteDoisCinco")
                        .HasColumnType("double precision");

                    b.Property<double?>("VinteDoisSeis")
                        .HasColumnType("double precision");

                    b.Property<double?>("VinteDoisZero")
                        .HasColumnType("double precision");

                    b.Property<double?>("VinteQuatroCinco")
                        .HasColumnType("double precision");

                    b.Property<double?>("VinteQuatroZero")
                        .HasColumnType("double precision");

                    b.Property<double?>("VinteUm")
                        .HasColumnType("double precision");

                    b.Property<double?>("VinteZero")
                        .HasColumnType("double precision");

                    b.HasKey("NumeroAlimento");

                    b.ToTable("AcidosGraxosTaco");
                });

            modelBuilder.Entity("PEACE.api.Models.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Fonte")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("QuantidadeReferencia")
                        .HasColumnType("double precision");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Alimentos");
                });

            modelBuilder.Entity("PEACE.api.Models.AminoacidosTaco", b =>
                {
                    b.Property<int>("NumeroAlimento")
                        .HasColumnType("integer");

                    b.Property<double?>("Alanina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Arginina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Aspartico")
                        .HasColumnType("double precision");

                    b.Property<double?>("Cistina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fenilalanina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Glicina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Glutamico")
                        .HasColumnType("double precision");

                    b.Property<double?>("Histidina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Isoleucina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Leucina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lisina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Metionina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Prolina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Serina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Tirosina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Treonina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Triptofano")
                        .HasColumnType("double precision");

                    b.Property<double?>("Valina")
                        .HasColumnType("double precision");

                    b.HasKey("NumeroAlimento");

                    b.ToTable("AminoacidosTaco");
                });

            modelBuilder.Entity("PEACE.api.Models.ItemConsumido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlimentoId")
                        .HasColumnType("integer");

                    b.Property<double>("QuantidadeGramas")
                        .HasColumnType("double precision");

                    b.Property<int>("RefeicaoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlimentoId");

                    b.HasIndex("RefeicaoId");

                    b.ToTable("ItensConsumidos");
                });

            modelBuilder.Entity("PEACE.api.Models.LoginAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastAttempt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("PEACE.api.Models.Nutricionista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Nutricionistas");
                });

            modelBuilder.Entity("PEACE.api.Models.NutrienteUSDA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlimentoUSDAId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomePadronizado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Subtipo")
                        .HasColumnType("integer");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AlimentoUSDAId");

                    b.ToTable("NutrientesUSDA");
                });

            modelBuilder.Entity("PEACE.api.Models.Refeicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Refeicoes");
                });

            modelBuilder.Entity("PEACE.api.Models.TabelaAlimentoUSDA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoIngles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescricaoTraduzida")
                        .HasColumnType("text");

                    b.Property<double>("QuantidadePadrao")
                        .HasColumnType("double precision");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlimentosUSDA");
                });

            modelBuilder.Entity("PEACE.api.Models.TabelaTaco", b =>
                {
                    b.Property<int>("NumeroAlimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NumeroAlimento"));

                    b.Property<double?>("Calcio")
                        .HasColumnType("double precision");

                    b.Property<double?>("Carboidrato")
                        .HasColumnType("double precision");

                    b.Property<double?>("Cinzas")
                        .HasColumnType("double precision");

                    b.Property<double?>("Cobre")
                        .HasColumnType("double precision");

                    b.Property<double?>("Colesterol")
                        .HasColumnType("double precision");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("EnergiaKcal")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnergiaKj")
                        .HasColumnType("double precision");

                    b.Property<double?>("Ferro")
                        .HasColumnType("double precision");

                    b.Property<double?>("FibraAlimentar")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fosforo")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lipideos")
                        .HasColumnType("double precision");

                    b.Property<double?>("Magnesio")
                        .HasColumnType("double precision");

                    b.Property<double?>("Manganes")
                        .HasColumnType("double precision");

                    b.Property<double?>("Niacina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Piridoxina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Potassio")
                        .HasColumnType("double precision");

                    b.Property<double?>("Proteina")
                        .HasColumnType("double precision");

                    b.Property<double?>("RAE")
                        .HasColumnType("double precision");

                    b.Property<double?>("RE")
                        .HasColumnType("double precision");

                    b.Property<double?>("Retinol")
                        .HasColumnType("double precision");

                    b.Property<double?>("Riboflavina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Sodio")
                        .HasColumnType("double precision");

                    b.Property<double?>("Tiamina")
                        .HasColumnType("double precision");

                    b.Property<double?>("Umidade")
                        .HasColumnType("double precision");

                    b.Property<double?>("VitaminaC")
                        .HasColumnType("double precision");

                    b.Property<double?>("Zinco")
                        .HasColumnType("double precision");

                    b.HasKey("NumeroAlimento");

                    b.ToTable("TabelaTaco");
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NutricionistaId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("NutricionistaId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Nutriente", b =>
                {
                    b.HasOne("PEACE.api.Models.Alimento", "Alimento")
                        .WithMany("Nutrientes")
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");
                });

            modelBuilder.Entity("PEACE.api.Models.AcidosGraxosTaco", b =>
                {
                    b.HasOne("PEACE.api.Models.TabelaTaco", "TabelaTaco")
                        .WithOne("AcidosGraxos")
                        .HasForeignKey("PEACE.api.Models.AcidosGraxosTaco", "NumeroAlimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabelaTaco");
                });

            modelBuilder.Entity("PEACE.api.Models.AminoacidosTaco", b =>
                {
                    b.HasOne("PEACE.api.Models.TabelaTaco", "TabelaTaco")
                        .WithOne("Aminoacidos")
                        .HasForeignKey("PEACE.api.Models.AminoacidosTaco", "NumeroAlimento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabelaTaco");
                });

            modelBuilder.Entity("PEACE.api.Models.ItemConsumido", b =>
                {
                    b.HasOne("PEACE.api.Models.Alimento", "Alimento")
                        .WithMany()
                        .HasForeignKey("AlimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PEACE.api.Models.Refeicao", "Refeicao")
                        .WithMany("ItensConsumidos")
                        .HasForeignKey("RefeicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alimento");

                    b.Navigation("Refeicao");
                });

            modelBuilder.Entity("PEACE.api.Models.NutrienteUSDA", b =>
                {
                    b.HasOne("PEACE.api.Models.TabelaAlimentoUSDA", "AlimentoUSDA")
                        .WithMany("Nutrientes")
                        .HasForeignKey("AlimentoUSDAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlimentoUSDA");
                });

            modelBuilder.Entity("PEACE.api.Models.Refeicao", b =>
                {
                    b.HasOne("Paciente", "Paciente")
                        .WithMany("Refeicoes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.HasOne("PEACE.api.Models.Nutricionista", "Nutricionista")
                        .WithMany("Pacientes")
                        .HasForeignKey("NutricionistaId");

                    b.Navigation("Nutricionista");
                });

            modelBuilder.Entity("PEACE.api.Models.Alimento", b =>
                {
                    b.Navigation("Nutrientes");
                });

            modelBuilder.Entity("PEACE.api.Models.Nutricionista", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("PEACE.api.Models.Refeicao", b =>
                {
                    b.Navigation("ItensConsumidos");
                });

            modelBuilder.Entity("PEACE.api.Models.TabelaAlimentoUSDA", b =>
                {
                    b.Navigation("Nutrientes");
                });

            modelBuilder.Entity("PEACE.api.Models.TabelaTaco", b =>
                {
                    b.Navigation("AcidosGraxos");

                    b.Navigation("Aminoacidos");
                });

            modelBuilder.Entity("Paciente", b =>
                {
                    b.Navigation("Refeicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
